# Generated by Django 5.2.1 on 2025-05-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='category',
            field=models.CharField(choices=[('investing', 'Investing'), ('trading', 'Trading')], default='investing', max_length=20),
        ),
    ]
